### ISSUE TITLE
Can not create internal repository (enterprise)

### ISSUE THREAD

**Issue by Timmmy-nlb** [octokit/plugin-rest-endpoint-methods.js#275]
**Describe the bug**
I am trying to create a repository in a workflow in an enterprise organization.
Unfortunately the parameter with the value 'visibility: "internal"' seems to be ignored.

**To Reproduce**
Using this code snippet

```
uses: actions/github-script@v3.0.0
[...]
const data = await github.repos.createInOrg({
    org: "test-org",
    name: "Test-Organisation",
    auto_init: true,
    visibility: "internal"
});
```

**Expected behavior**
A repo should be created, which has the status internal, instead a public one is created.

(Coming from [github-script/#94)](https://github.com/actions/github-script/issues/94)

**Comment by gr2m** [comment]
To use the `visibility` parameter, you have to enable the `nebula` preview.

Try this

```js
const data = await github.repos.createInOrg({
    mediaType: {
        previews: ["nebula"]
    },
    org: "test-org",
    name: "Test-Organisation",
    auto_init: true,
    visibility: "internal"
});
```

**Comment by Timmmy-nlb** [comment]
Yes, thats works! 
Thank you very much for this good/quick answer.
