### ISSUE TITLE
npm version 2.4.0

### ISSUE THREAD

**Issue by w3nda** [octokit/plugin-rest-endpoint-methods.js#29]
**What happened?**
```bash
Couldn't find any versions for "@octokit/plugin-rest-endpoint-methods" that matches "2.4.0"
```

**What did you expect to happen?**
To install it with no errors

**What the problem might be**
My findings so far are that yesterday this issue didn’t happen, then earlier today (6 hours ago) you released this version `@octokit/plugin-rest-endpoint-methods@2.4.0`, which got me thinking maybe it’s (flushing, npm publish, idk), so I checked at npm  *WEBSITE* and it did release properly and the latest tag is on `2.4.0`

Afterwards I ran `npm view @octokit/plugin-rest-endpoint-methods versions`  and that’s where all the fun begins, the response doesn’t contain version `2.4.0`

Thanks in advance :)

**Comment by w3nda** [comment]
Sorry for false info, this issue happened because our corporate npm registry didn't update since your last publish. closing <3

**Comment by gr2m** [comment]
Thanks for the update, good to know that this might be an issue, I'll think of that as a potential cause for future bug reports 👍
