### ISSUE TITLE
TypeScript compilation issues in probot/octokit with 4.13.1

### ISSUE THREAD

**Issue by bcoe** [octokit/plugin-rest-endpoint-methods.js#354]
**What happened?**

The latest release of `plugin-rest-endpoint-methods` is causing compilation errors for `@octokit/rest` and `probot`:

```
node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1761:60 - error TS2339: Property 'POST /repos/{owner}/{repo}/environments/{environment_name}' does not exist on type 'Endpoints'.

1761             parameters: RequestParameters & Omit<Endpoints["POST /repos/{owner}/{repo}/environments/{environment_name}"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1762:33 - error TS2339: Property 'POST /repos/{owner}/{repo}/environments/{environment_name}' does not exist on type 'Endpoints'.

1762             response: Endpoints["POST /repos/{owner}/{repo}/environments/{environment_name}"]["response"];
```

See: https://github.com/googleapis/release-please/pull/805, https://github.com/googleapis/repo-automation-bots/pull/1462

**What did you expect to happen?**

Compilation should not throw errors 

**What the problem might be**

**Comment by gr2m** [comment]
I had a little booboo there with the `POST /repos/{owner}/{repo}/environments/{environment_name}` endpoint, but I thought I resolved it yesterday. Could you please upgrade to the latest versions?

**Comment by bcoe** [comment]
Re-running tests is green:

https://github.com/googleapis/release-please/pull/805

Sorry for not trying that first.

**Comment by gr2m** [comment]
no problem at all, I'm sorry for the noise, I don't know how that one slipped, it really should not. The `POST /repos/{owner}/{repo}/environments/{environment_name}` endpoint was added but shortly after removed from the OpenAPI spec (it was still in beta preview at this point). I was the one who caught it and deliberately ignored the update, but somehow missed that the next update still had the route. Again, sorry for that, this was a very unusual situation, it shouldn't occur again
