### ISSUE TITLE
"cancelInvitation" not found

### ISSUE THREAD

**Issue by Timmmy-nlb** [octokit/plugin-rest-endpoint-methods.js#403]
I get error `Unhandled error: TypeError: github.orgs.cancelInvitation is not a function` with this code:

```javascript
- name: CancelInvitation
  uses: actions/github-script@v4
  [...]
  script: |
       github.orgs.cancelInvitation({
                org: "organization",
                invitation_id: 00000,
        });
```

A call from `console.log('Test: ', github.orgs);` shows that the method is really missing.

Another little question:
I use allway in my GH-Workflows the octokit methods  with "github." instead of "octokit.rest." 
Wrong?

**Comment by gr2m** [comment]
I cannot help with https://github.com/actions/github-script, can you file an issue at their repository please? I don't know which version of `@octokit/plugin-rest-endpoint-methods` they are using.

**Comment by Simran-B** [comment]
They are currently at 4.2.1, latest release here is 5.3.2, so quite a bit lagging behind.
