### ISSUE TITLE
Typo updateStatusCheckPotection

### ISSUE THREAD

**Issue by ruggi99** [octokit/plugin-rest-endpoint-methods.js#436]
https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/3fd0754b525f9bf14f5987e89e3ec616261ce71d/src/generated/endpoints.ts#L1303

I think I've found a typo in this method name

**Comment by gr2m** [comment]
It’s the for legacy reasons, burnouts deprecated. We just don’t remove methods outside of a breaking change version, we will remove it with the next one
