### ISSUE TITLE
Incorrect type for setLabels

### ISSUE THREAD

**Issue by tomasreimers** [octokit/plugin-rest-endpoint-methods.js#461]
**What happened?**

The type inferred for setLabels is incorrect. It is constrained to: 

```
string[] & {
  name: string
}[]
```

**What did you expect to happen?**

 It should be: 

```
string[] | {
  name: string
}[]
```

As the API documentation specifies that you can pass either an array of strings, or an array of objects that have names (as opposed to an array which satisfies both). 

**What the problem might be**

The definition appears to be: 

```
"issues/set-labels": {
    parameters: {
      path: {
        owner: components["parameters"]["owner"];
        repo: components["parameters"]["repo"];
        /** issue_number parameter */
        issue_number: components["parameters"]["issue_number"];
      };
    };
    responses: {
      /** Response */
      200: {
        content: {
          "application/json": components["schemas"]["label"][];
        };
      };
      410: components["responses"]["gone"];
      422: components["responses"]["validation_failed"];
    };
    requestBody: {
      content: {
        "application/json": Partial<{
          /** The names of the labels to add to the issue. You can pass an empty array to remove all labels. **Note:** Alternatively, you can pass a single label as a `string` or an `array` of labels directly, but GitHub recommends passing an object with the `labels` key. */
          labels?: string[];
        }> &
          Partial<{
            labels?: {
              name: string;
            }[];
          }>;
      };
    };
  };
```

**Comment by gr2m** [comment]
This should have been resolved via https://github.com/octokit/openapi/pull/155.

Can you share the output of ` npm ls | grep -v deduped | grep octokit` if you use a unix-based system? Otherwise just the output of `npm ls @octokit/plugin-rest-endpoint-methods` and `npm ls @octokit/openapi-types`

**Comment by wolfy1339** [comment]
This issue is now almost a year old, with no response.
If the issue still happens, feel free to comment
