### ISSUE TITLE
Compile error regarding rest endpoint method types

### ISSUE THREAD

**Issue by karmann-dm** [octokit/plugin-rest-endpoint-methods.js#488]
I am trying to compile the GH integration code with the following dependencies:
```
"dependencies": {
    "@octokit/types": "^6.37.0",
    "@octokit/rest": "^18.12.0",
    "@octokit/plugin-paginate-rest": "^2.19.0",
    "@octokit/plugin-rest-endpoint-methods": "^5.15.0"
  },
  "devDependencies": {
    "eslint": "^7.8.1",
    "typescript": "^3.9.7",
    "@zeit/ncc": "^0.22.3"
  }
```
NodeJS version 14.19.1, npm version 6.14.16

**What happened?**
An error is thrown on the compile stage
```
> tsc

node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:437:60 - error TS2339: Property 'POST /content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.

437             parameters: RequestParameters & Omit<Endpoints["POST /content_references/{content_reference_id}/attachments"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:438:33 - error TS2339: Property 'POST /content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.

438             response: Endpoints["POST /content_references/{content_reference_id}/attachments"]["response"];
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:441:60 - error TS2339: Property 'POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.

441             parameters: RequestParameters & Omit<Endpoints["POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:442:33 - error TS2339: Property 'POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.

442             response: Endpoints["POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments"]["response"];
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.

```

**What did you expect to happen?**

Compilation without errors.

**What the problem might be**

I suspect that it is somehow related to [this issue](https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/172), but I have version that were issued much lated than the ones described in the fix of this issue.

**Comment by wolfy1339** [comment]
Can you please share your `tsconfig.json` as well?

**Comment by timrogers** [comment]
Could you also check what version of `@octokit/plugin-rest-endpoint-methods` is in `node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods` by checking `node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/package.json`? Judging by the error, I think it isn't the current version (v5.15.0).

**Comment by timrogers** [comment]
> @timrogers
> 
> > Could you also check what version of @octokit/plugin-rest-endpoint-methods
> 
> Yes, seems like, do you have an idea how to fix it?
> 
> ```
> $ cat node_modules/@octokit/rest/node_modules/@octokit/plugin-rest-endpoint-methods/package.json | grep \"version\":
>   "version": "5.13.0"
> ```

Interesting! I wonder if we need to update the dependency defined on `@octokit/rest`. The links between all of these packages are pretty tricky to understand.

@gr2m Can you point us in the right direction?

**Comment by gr2m** [comment]
The `POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments` endpoint has been removed. You likely have the latest version of `@octokit/openapi-types`, but not the latest version of `@octokit/plugin-rest-endpoint-methods`.

Try to delete the `node_modules` folder and whatever lock file you use (usually `package-lock.json`). Then run `npm install` again, that should fix it

**Comment by a-tarasyuk** [comment]
[TypeScript](https://github.com/microsoft/TypeScript) uses the latest version of `@octokit/rest`., today I noticed that the [CI build failed](https://github.com/microsoft/TypeScript/runs/7161986346?check_suite_focus=true) due to the following errors

```shell
Error: node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(903,48): error TS2344: Type '"/orgs/{org_id}/codespaces"' does not satisfy the constraint 'keyof paths'.
Error: node_modules/@octokit/types/dist-types/generated/Endpoints.d.ts(1612,70): error TS2344: Type '"/repos/{owner}/{repo}/community/code_of_conduct"' does not satisfy the constraint 'keyof paths'.
Error: node_modules/@octokit/plugin-paginate-rest/dist-types/generated/paginating-endpoints.d.ts(226,74): error TS2339: Property 'data' does not exist on type 'unknown'.

```
I'm not sure if this is related to this issue or should I create a new one?

**Comment by timrogers** [comment]
@a-tarasyuk Can you try updating all of the Octokit packages? I think you'll find this is fixed now.

**Comment by a-tarasyuk** [comment]
It uses the latest version. Has it been updated recently?

```json
"@octokit/rest": "latest",
```

**Comment by timrogers** [comment]
Yep! I have just released updates to several Octokit packages. Can you tell me the versions of all of your Octokit-related packages in your lock file?

**Comment by a-tarasyuk** [comment]
@timrogers Thanks. The latest version seems to work fine.

**Comment by timrogers** [comment]
Great - sorry about that! The packages have complicated dependencies and some of them still needed updates.
