### ISSUE TITLE
Suspend a users on GHES?

### ISSUE THREAD

**Issue by IAmHughes** [octokit/plugin-rest-endpoint-methods.js#577]
We were unable to find the [enterprise-admin/users#suspend-a-user](https://docs.github.com/en/enterprise-server@3.5/rest/enterprise-admin/users#suspend-a-user) endpoint

As a GHES admin, I want to use Octokit.js to be able to suspend my users. This endpoint exists, and I can use the Octokit.request method, however I'd love to have the helper wrapper in this plugin.

/cc @wilsonwong1990

**Comment by gr2m** [comment]
We have a dedicated plugin for GHES versions, does that help?
https://github.com/octokit/plugin-enterprise-server.js/#readme

Bundle size is important in JS land, so we don't ship GHES endpoints default in this plugin

**Comment by IAmHughes** [comment]
Thanks @gr2m , apologies, didn't see that plugin. Is there a top level page for plugins? 😓 

Also, if I'm reading that correctly, we would need to update our script every GHES version to instantiate the proper plugin? There's no generic way to instantiate without specifying a version (since this endpoint has existed forever, I'm not expecting it to change versions?).

Not a huge issue, just something we need to note and a pain point that every future GHES upgrade will mean a different instantiation....or if I run the script on multiple GHES servers I have to now handle instantiation based on version of the server 😬

**Comment by gr2m** [comment]
> Is there a top level page for plugins?

I wish 😭

> Also, if I'm reading that correctly, we would need to update our script every GHES version to instantiate the proper plugin?

Unfortunately, yes. Personally, I wouldn't rely on the helper methods at all, I'd use `octokit.request`.

--

What is your use case? 1st class GHES support is a big focus on https://github.com/octokit/octokit-next.js, it would be interesting to know if your use case is covered in Octokit Next

**Comment by IAmHughes** [comment]
Thanks @gr2m, no worries!

> What is your use case?

Fairly simple use case. GHES has the concept of dormant users, however GitHub hasn’t implemented a feature to have an “allow-list” to exempt certain accounts from becoming dormant. This is commonly an issue with service accounts that only do API tasks which don’t log as activity in the GHES database and therefore show they are dormant.

In order to “suspend all dormant users” like the UI allows, we need to write a simple helper tool to do the suspending with a caveat of checking an allow list first, so our dormant users are suspended but service accounts are kept active.

**Comment by gr2m** [comment]
Got it. Yes, I think that should be possible in Ocotkit Next.js, you could do something like this: [TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAWgDsBTADxgHpVomyAoX0JFjkqNbDEasOMAJ5gmAZzpRFEgIZhgdAOYALRXQDMAOgAsfQdHiVqGcZLbtZ8pSoXrNO-UpMBWC+BWIra0EsyOzgZuHlp6BiYAbHy87Ozk2ji6AK4ARsZcIGRwmEwycAAmEIpwagA2AO5qMgpwrMDucDll5UwEalm1MLyRcADKWWBCMEzlAOIAEgCiowBqTFAKwBAMLQC8cIssqLVZPQA8JTIQBChiOMYAgpprG1s7ADTpmbn5JGQAfPwesc1Co4FwdvAmAwAG4ALkQvDgcAWywA+itFgAlUYASWQADkEeNJlYZqjVutNtsFO8kSilqM0QAhB6jRZogCqWIAMgj3FBgAxtHTkRS0Q8ACIAWVxBLRABVkABpRZEuACoXaXi4fgQjohcRwfbMeq3Ow4AAUSHpMKpbwR0JhxnFmJx+IJopqWRgukdsJdjIlMrlipVaq9OTUCiYnKgtX9zvFUtl8qVqoJOoAlPxUnBqBAYOJjCoAI5ZVSWrNwBgQM3bWplBRZbTaVQtYg+6q+tRQljteBCuCWWAzBnLOB2140mo5CB2lJpJWS5AI+pMOAgYB6eD64A9KBweRQLcwGBa-MMRvFWv1BhwTvTFoEaBwEYKNQEJiyXj6+BuSAdg3fY1EaHB8zuGASyYctKzISVFh5RYFUWOB2DUcotwYdgshjDZ2AQXD1gYNQQCYXAyE+BB6SIqASLIhEyD4XAsyAA) 

For now, I'd recommend to just use https://github.com/octokit/core.js and `octokit.request()`
