### ISSUE TITLE
Generated response types are incorrect for some values

### ISSUE THREAD

**Issue by joeyj-deliveroo** [octokit/plugin-rest-endpoint-methods.js#64]
**What happened?**

Current entry in @octokit/plugin-rest-endpoint-methods/dist-types/generated/types.d.ts:
```
declare type SearchIssuesAndPullRequestsResponseItemsItem = {
    assignee: null;
    body: string;
    closed_at: null;
    comments: number;
    comments_url: string;
    created_at: string;
    events_url: string;
    html_url: string;
    id: number;
    labels: Array<SearchIssuesAndPullRequestsResponseItemsItemLabelsItem>;
    labels_url: string;
    milestone: null;
    node_id: string;
    number: number;
    pull_request: SearchIssuesAndPullRequestsResponseItemsItemPullRequest;
    repository_url: string;
    score: number;
    state: string;
    title: string;
    updated_at: string;
    url: string;
    user: SearchIssuesAndPullRequestsResponseItemsItemUser;
};
```

**What did you expect to happen?**

I'd expect `closed_at` to be `string | null`. I'm unsure about the other `null` types as well.

**Comment by gr2m** [comment]
These types are currently automatically generated from the documentation at https://developer.github.com/v3/, via https://github.com/octokit/routes/. In this particular case from the response at https://developer.github.com/v3/search/#example-3.

We are looking into ways to get better response schemas, but for the time being this is the best we can do. 

You'll have to manually overwrite the type, e.g. `response.data.closedAt as string`

**Comment by ockham** [comment]
FWIW, I'm facing the same issue (`closed_at` being typed as `null`) with `IssuesListForRepoResponseItem`.

**Comment by wolfy1339** [comment]
@ockham What version are you using?

The types are generated from [GitHub's OpenAPI spec for the REST API](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json) now, can you check the endpoint there and see if the problem is there as well

**Comment by ockham** [comment]
> @ockham What version are you using?

16.26.0

> The types are generated from [GitHub's OpenAPI spec for the REST API](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json) now, can you check the endpoint there and see if the problem is there as well

Ah, I wasn't aware, thanks for the pointer!

The latest version -- v18.1.1-- seems to have the right type for issues list items indeed (with the `closed_at` field's type set to a string) :tada: But alas, the [new type format](https://github.com/octokit/types.ts/tree/63fd0dcd31c1a547170ccdb72e7885a9b4080745#examples) doesn't seem to work too well with TS-in-JSDoc :confused: I've filed an [experimental PR](https://github.com/WordPress/gutenberg/pull/29043), describing the issue in the PR desc, if either of you could maybe have a quick look :blush: 

Is there any other (more JSDoc-compatible) way to access these types?

**Comment by wolfy1339** [comment]
I believe that the original issue here has been resolved.
