### ISSUE TITLE
[BUG]: No way to add new methods to octokit.rest.repos in v7

### ISSUE THREAD

**Issue by mheap** [octokit/plugin-rest-endpoint-methods.js#668]
### What happened?

I maintain [octokit-commit-multiple-files](https://github.com/mheap/octokit-commit-multiple-files), which has stopped working with `plugin-rest-endpoint-methods.js` 7.0. (Bug report: https://github.com/mheap/octokit-commit-multiple-files/issues/110)

It seems to be related to the refactoring in https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/622

I previously attached a new method to `octokit.rest.repos` like so:

```javascript
module.exports = function (octokit) {
  octokit.rest.repos.createOrUpdateFiles = plugin.bind(null, octokit);
};
```

Is there a way to register new methods after this refactoring?

### Versions

@octokit/rest 19.0.7
Node.js v18.15.0

### Relevant log output

```shell
/private/tmp/octokit-test/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:1929
    const { decorations, endpointDefaults } = endpointMethodsMap.get(scope).get(methodName);
            ^

TypeError: Cannot destructure property 'decorations' of 'endpointMethodsMap.get(...).get(...)' as it is undefined.
    at Object.get (/private/tmp/octokit-test/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:1929:13)
    at /private/tmp/octokit-test/index.js:14:44
    at Object.<anonymous> (/private/tmp/octokit-test/index.js:32:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
the correct way to define methods is to export an object where the keys are the methods that should be added to `octokit`:
https://github.com/octokit/core.js/#plugins

You cannot rely on `octokit.rest.repos.` to exist, it would make your plugin incompatible with `@octokit/core`

**Comment by mheap** [comment]
If I want to add a method to `octokit.rest.repos` explicitly, how can I do so?

```javascript
module.exports = function (octokit) {
  return {
    rest: {
      repos: {
        ...octokit.rest.repos,
        createOrUpdateFiles: plugin.bind(null, octokit),
      },
    },
  };
};
```

This has the same error:

```
    TypeError: Cannot destructure property 'decorations' of 'endpointMethodsMap.get(...).get(...)' as it is undefined.

       5 |     rest: {
       6 |       repos: {
    >  7 |         ...octokit.rest.repos,
         |                         ^
       8 |         createOrUpdateFiles: plugin.bind(null, octokit),
       9 |       },
      10 |     },
```

Or is the recommendation not to attach at that point, and to make `octokit.createOrUpdateFiles` the method to call?

**Comment by gr2m** [comment]
> If I want to add a method to `octokit.rest.repos` explicitly, how can I do so?

I'm sorry but the best answer I have is you shouldn't, as I explained above. Plugins should declare top level methods, in your case it would be `octokit.createOrUpdateFiles()`. The `octokit.rest.*` methods have other APIs that yours doesn't have, like `octokit.rest.repos.get.endpoint()`. Please avoid mingling with the `.rest` namespace

**Comment by mheap** [comment]
Thanks for the info. I've moved the method to the object root in the plugin

**Comment by gr2m** [comment]
Thank you! I'll make sure to add note to plugin docs
