### ISSUE TITLE
[BUG]: CommonJS `require()` is broken.

### ISSUE THREAD

**Issue by manchicken** [octokit/plugin-rest-endpoint-methods.js#744]
### What happened?

I just upgraded, and it looks like the updated version (13.2.1) breaks compatibility with CommonJS `require()`.

This line of code:

```js
const { restEndpointMethods } = require('@octokit/plugin-rest-endpoint-methods')
```

Results in this exception:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module
```

Typically modules like this would have a version which is suitable for both ESM and CJS, and this _used_ to have that (in 10.2.0).

### Versions

I'm on Node v22.2.0, and here's the diff in the `package-lock.json`:

```diff
-        "@octokit/plugin-paginate-rest": "^9.1.5",
-        "@octokit/plugin-rest-endpoint-methods": "^10.2.0",
-        "@octokit/plugin-throttling": "^8.1.3",
-        "@octokit/rest": "^20.0.2",
+        "@octokit/plugin-paginate-rest": "^11.3.0",
+        "@octokit/plugin-rest-endpoint-methods": "^13.2.1",
+        "@octokit/plugin-throttling": "^9.3.0",
+        "@octokit/rest": "^20.1.1",
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is expected. This package has migrated to only ESM.

**Comment by gr2m** [comment]
> -        "@octokit/plugin-paginate-rest": "^9.1.5",
> -        "@octokit/plugin-rest-endpoint-methods": "^10.2.0",
> -        "@octokit/plugin-throttling": "^8.1.3",
> -        "@octokit/rest": "^20.0.2",
> +        "@octokit/plugin-paginate-rest": "^11.3.0",
> +        "@octokit/plugin-rest-endpoint-methods": "^13.2.1",
> +        "@octokit/plugin-throttling": "^9.3.0",
> +        "@octokit/rest": "^20.1.1",

you shouldn't need to import the paginate and rest endpoint methods plugins, they are all included in `@octokit/rest`:
https://github.com/octokit/rest.js/blob/main/src/index.ts

Just update `@octokit/plugin-throttling`, but stay below [v9 which migrated to ESM](https://github.com/octokit/plugin-throttling.js/releases/tag/v9.0.0)

**Comment by wolfy1339** [comment]
Every major version contains breaking changes. Updating without reading the release notes is bad

Unfortunately, this is the way the ecosystem is going, and has been a direction we were planning to pursue for a while

**Comment by manchicken** [comment]
> you shouldn't need to import the paginate and rest endpoint methods plugins, they are all included in `@octokit/rest`: https://github.com/octokit/rest.js/blob/main/src/index.ts

I'll look into that.

> Just update `@octokit/plugin-throttling`, but stay below [v9 which migrated to ESM](https://github.com/octokit/plugin-throttling.js/releases/tag/v9.0.0)

I don't think they've so much migrated to ESM so much as they've just made the choice to require their users to do so.

**Comment by gr2m** [comment]
We have to migrate to ESM as the ecosystem is migrating to ESM. You should upgrade as well in order to avoid to get stuck with dependencies that have known security problems.

Your last comment confusing and unnecessarily confrontational. I understand the ESM transition is causing friction like it does for everyone.

If you are stuck with CommonJS for a while, that's ok. We will backport security fixes to the older versions, and you are free to submit pull requests against these older versions.

**Comment by manchicken** [comment]
> We have to migrate to ESM as the ecosystem is migrating to ESM. You should upgrade as well in order to avoid to get stuck with dependencies that have known security problems.

Why do y'all keep saying that the ecosystem is migrating to ESM when most major modules still support CJS, and all major runtimes still maintain support for CJS? While I understand some folks have a preference for one over the other, I haven't seen anybody adopting the stance that this project now is.
