### ISSUE TITLE
ChecksListSuitesForRefResponseCheckSuitesItem is missing keys

### ISSUE THREAD

**Issue by sean-krail** [octokit/plugin-rest-endpoint-methods.js#8]
**What happened?**

The `ChecksListSuitesForRefResponseCheckSuitesItem` type is missing keys that exist in the actual object. They are:
- created_at
- updated_at
- latest_check_runs_count
- check_runs_url
- head_commit

And are missing from the documention at https://developer.github.com/v3/checks/suites/#list-check-suites-for-a-specific-ref

**What did you expect to happen?**

The keys to exist.

**What the problem might be**

How this repo generates its types.

---

Reproduced on runkit at https://runkit.com/sean-krail/octokit-plugin-rest-endpoint-methods.js

**Comment by gr2m** [comment]
The code & types are generated based on https://github.com/octokit/routes/, which scrapes the documentation at https://developer.github.com/v3/. 

If the keys are missing in the docs, could you send an email to support@github.com? They will forward it to the right people. It would help if you would send along a `curl` request with the response showing the keys. Once the documentation is fixed, this repo will get updated automatically trough an update of `@octokit/routes`

**Comment by sean-krail** [comment]
Created a GHE support ticket for this and here's a `curl` + `jq` request you can make to show you the response's keys/structure:

```bash
curl --silent --header 'Accept: application/vnd.github.antiope-preview+json' \
    "https://api.github.com/repos/octokit/plugin-rest-endpoint-methods.js/commits/master/check-suites" \
  | jq --raw-output '.check_suites[0]' \                                        
  | less
```

**Comment by gr2m** [comment]
You can get the types from `@octokit/openapi-types` now

```ts
import { components } from "@octokit/openapi-types"

type CheckSuite = components["schemas"]["check-suite"]
const test: CheckSuite = {
    created_at: "",
    updated_at: "",
    latest_check_runs_count: 1,
    check_runs_url: "",
    head_commit: {},
    // ...
}
```

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYwuCA7AphmBnOAXzgDMo04AiAAQmRggGtgYB6CMHAQzGAFoYAT055KAKDGoMeeDCwy4AXkRi4alFCxc5AEwD62gFxVKAGlXqArmB3as+oyfPq4AGzsy9yABZZkjPShLaS8IYJhjAEZndR8-AKCQyyhXY0ozCzVfLn1UEBAWYwRCMWIuAjzIbFw8AG1KPDiQcsoAXXq4-z48SxYsNqA)
