### ISSUE TITLE
Gist update is not working as expect

### ISSUE THREAD

**Issue by cwxyz007** [octokit/plugin-rest-endpoint-methods.js#83]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [ ] Node.js
- [x] Browsers: chrome Version 80.0.3987.149 (Official Build) (64-bit)
- [ ] Others: 

**Versions**

```
├─┬ @octokit/rest@17.9.0
│ ├─┬ @octokit/core@2.5.0
│ │ ├─┬ @octokit/auth-token@2.4.0
│ │ ├─┬ @octokit/graphql@4.4.0
│ │ ├─┬ @octokit/request@5.4.2
│ │ │ ├─┬ @octokit/endpoint@6.0.1
│ │ │ ├─┬ @octokit/request-error@2.0.0
│ │ ├─┬ @octokit/types@2.16.0
│ ├─┬ @octokit/plugin-paginate-rest@2.2.0
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@3.11.0
```

**What happened?**

The following code is not working.

```js
async function start() {
  const git = new Octokit({
    auth: 'xxx'
  })
  await git.gists.update({
    gist_id: id,
    files: {
      content: 'update from api',
      filename: 'postcss.config.js'
    }
  })
}

start()
```
![image](https://user-images.githubusercontent.com/14226737/81718428-51740600-94ae-11ea-9a21-33d908dc9db3.png)

**Minimal test case to reproduce the problem**
```js
import { Octokit } from '@octokit/rest'
async function start() {
  const git = new Octokit({
    auth: 'xxx'
  })
  await git.gists.update({
    gist_id: id,
    files: {
      content: 'update from api',
      filename: 'postcss.config.js'
    }
  })
}

start()

```

**What did you expect to happen?**

Working correctly.

**What the problem might be**

Wrong type define and document.

The official document is: https://developer.github.com/v3/gists/#update-a-gist

And the type define should be:

```ts
type GistsUpdateEndpoint = {
  /**
   * gist_id parameter
   */
  gist_id: string;
  /**
   * A descriptive name for this gist.
   */
  description?: string;
  /**
   * The filenames and content that make up this gist.
   */
  files?: {
    [filename:string]: GistsUpdateParamsFiles
  };
};
```

**Comment by gr2m** [comment]
I need to update `@octokit/rest` to use this version before it will be resolved there, I'm on it
