### ISSUE TITLE
Enum types in responses are being generically typed as string

### ISSUE THREAD

**Issue by sean-krail** [octokit/plugin-rest-endpoint-methods.js#9]
**What happened?**

There are enum types are being specified as `string` when they are really string enums.

**What did you expect to happen?**

That these enum types are specified as string enums. For example:
```typescript
enum CheckRunStatus {
  queued = 'queued',
  in_progress = 'in_progress',
  completed = 'completed'
}
export enum CheckSuiteConclusion {
  action_required = 'action_required',
  cancelled = 'cancelled',
  timed_out = 'timed_out',
  failure = 'failure',
  neutral = 'neutral',
  success = 'success'
}
...
type ChecksListSuitesForRefResponseCheckSuitesItem = {
  ...
  conclusion: CheckSuiteConclusion;
  status: CheckRunStatus
};
```
vs.
```typescript
type ChecksListSuitesForRefResponseCheckSuitesItem = {
  ...
  conclusion: string;
  status: string
};
```

**What the problem might be**

How this repo generates its types.

**Comment by gr2m** [comment]
I agree, that would be nice. Would you like to try send a pull request?

**Comment by sean-krail** [comment]
This seems related to #8 in that the enums values aren't documented well (at least for a scraper to pick up). `CheckRunStatus` is in https://developer.github.com/v3/checks/runs/ and `CheckSuiteConclusion` in https://developer.github.com/v3/checks/suites/.

Not to rant about the quality of the docs, but they get really confusing at times. The graphic showing all of the conclusions shows "canceled" and "failed" (https://developer.github.com/assets/images/check_suites.png), but the actual values are "cancelled" and "failure".

**Comment by gr2m** [comment]
I now better understand your request, I thought it was about request parameter types, not response types. There is in fact very little we can do about response types at this point.

But there is hope. GitHub is working on an official OpenAPI specification, it will likely have much better response types, as they don't need to be derived from a single response example.

But right now I'm afraid there is nothing we can do

> The graphic showing all of the conclusions shows "canceled" and "failed" (https://developer.github.com/assets/images/check_suites.png), but the actual values are "cancelled" and "failure".

Definitely let the team now via support@github.com. The team behind it is really great, it's just very hard to stay on top of everything. It's very helpful and appreciated to get pointers like yours

**Comment by sean-krail** [comment]
An OpenAPI specification would be amazing! I'll send that support ticket over and I totally understand the struggle of keeping docs up to date.

**Comment by gr2m** [comment]
We now have an official OpenAPI spec, and types generated from that spec, e.g. 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/39992/123559444-e6889b80-d750-11eb-840a-fa3f04afadd2.png">

<img width="712" alt="image" src="https://user-images.githubusercontent.com/39992/123559461-fbfdc580-d750-11eb-98dc-b077c7ae4c46.png">

Let me know if you have any further questions
